[bans]
multiple-versions = "allow"
deny = []

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Zlib",
    "Unicode-3.0",
    "Unlicense",                      # https://unlicense.org/
]


[advisories]
ignore = []
